### ISSUE TITLE
The camera is closing in the video tab using the Portuguese language Brazil.

### ISSUE THREAD

**Issue by antmasterkey** [RicardoGuariento/MIUI-XML-13-BRAZILIAN#3]
The camera is closing in the video tab using the Portuguese language Brazil.

I took the test in other languages, and it was normal.

POCO F3

**Comment by DiorgenesS** [comment]
Qual a versão exata da Miui?
Pode anexar um logcat com o erro?

**Comment by antmasterkey** [comment]
Xiaomi.eu miui 13 22.5.11

**Comment by antmasterkey** [comment]
java.util.IllegalFormatConversionException: f != java.lang.Integer
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4403)
	at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2898)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2845)
	at java.util.Formatter.format(Formatter.java:2524)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2911)
	at android.content.res.Resources.getString(Unknown Source:19)
	at android.content.Context.getString(Unknown Source:4)
	at com.android.camera.data.data.config.ComponentConfigVideoQuality.initVideoMode(Unknown Source:264)
	at com.android.camera.data.data.config.ComponentConfigVideoQuality.initItem(Unknown Source:214)
	at com.android.camera.data.data.config.ComponentConfigVideoQuality.reInit(Unknown Source:44)
	at com.android.camera.data.data.config.ComponentConfigVideoQuality.getComponentValue(Unknown Source:25)
	at com.android.camera.data.data.config.ComponentConfigVideoQuality.getComponentValue(Unknown Source:2)
	at com.android.camera.CameraSettings.isVideoQuality8KOpen(Unknown Source:8)
	at com.android.camera.module.loader.camera2.Camera2DataContainer.getActualOpenCameraId(Unknown Source:1021)
	at com.android.camera.module.loader.camera2.Camera2DataContainer.getCapabilitiesByBogusCameraId(Unknown Source:1)
	at com.android.camera.fragment.DispatchFragment.reInitData(Unknown Source:98)
	at com.android.camera.fragment.DispatchFragment.provideAnimateElement(Unknown Source:44)
	at com.android.camera.animation.AnimationComposite.dispose(Unknown Source:94)
	at com.android.camera.fragment.BaseFragmentDelegate.delegateMode(Unknown Source:48)
	at com.android.camera.Camera.onModeSelected(Unknown Source:503)
	at com.android.camera.fragment.modeselector.FragmentModeSelector.changeModeByNewMode(Unknown Source:227)
	at com.android.camera.fragment.modeselector.FragmentModeSelector.onModeSelected(Unknown Source:65)
	at com.android.camera.ui.ModeSelectView.onScrollStateChanged(Unknown Source:128)
	at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(Unknown Source:7)
	at androidx.recyclerview.widget.RecyclerView.setScrollState(Unknown Source:13)
	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(Unknown Source:432)
	at com.android.camera.ui.ModeSelectView.onTouchEvent(Unknown Source:23)
	at android.view.View.dispatchTouchEvent(Unknown Source:97)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:39)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:590)
	at com.android.camera.ui.ModeSelectView.dispatchTouchEvent(Unknown Source:25)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at com.android.camera.ui.DragLayout.dispatchTouchEvent(Unknown Source:62)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at com.android.camera.ui.CameraRootView.dispatchTouchEvent(Unknown Source:19)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:628)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(Unknown Source:0)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(Unknown Source:2)
	at android.app.Activity.dispatchTouchEvent(Unknown Source:13)
	at com.android.camera.Camera.dispatchTouchEvent(Unknown Source:39)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(Unknown Source:123)
	at android.view.View.dispatchPointerEvent(Unknown Source:16)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(Unknown Source:45)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:131)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:26)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
	at android.view.ViewRootImpl.deliverInputEvent(Unknown Source:165)
	at android.view.ViewRootImpl.doProcessInputEvents(Unknown Source:48)
	at android.view.ViewRootImpl.enqueueInputEvent(Unknown Source:165)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(Unknown Source:110)
	at android.view.InputEventReceiver.dispatchInputEvent(Unknown Source:36)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(Unknown Source:17)
	at android.view.ViewRootImpl.doConsumeBatchedInput(Unknown Source:4)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(Unknown Source:13)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:84)
	at android.view.Choreographer.doFrame(Unknown Source:294)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)

**Comment by IgorEisberg** [comment]
Your mistake was writing %fps instead of %dfps, like in the default values...
